name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
        docker build -t gauge-taiko . && \
        docker run  --rm -it -v ${PWD}/reports:/gauge/reports gauge-taiko
